name: ruang_meeting
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.6
  intl: ^0.18.1
  firebase_core: ^2.24.2
  firebase_auth: ^4.17.5
  cloud_firestore: ^4.17.5
  cloud_functions: ^4.6.5


dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/bg_meeting.jpg
    - assets/bg_landing.jpg
    - assets/bg_landing2.jpg
    - assets/bg_landing3.jpg
    - assets/logo.PNG
    